In [310]:
import pandas as pd
df=pd.read_csv('NPPE1_Preprocessing1.csv')

In [311]:
df.shape

(4000, 14)

In [312]:
df.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO

In [313]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'POLINDEX', 'RM', 'AGE', 'DIS', 'HIGHWAYCOUNT',
       'TAX', 'PTRATIO', 'IMM', 'BPL', 'PRICE', 'RIVERSIDE'],
      dtype='object')

In [314]:
df['PRICE'].describe()

count    4000.000000
mean       24.355923
std         8.633523
min         6.348266
25%        19.259094
50%        22.634566
75%        26.947036
max        53.090256
Name: PRICE, dtype: float64

In [315]:
df['PRICE'].mean()

np.float64(24.355923220694248)

In [316]:
g=df[(df['RM']>=5)]
g['RM'].count()

np.int64(3953)

In [317]:
# g=df['PRICE'].ASCENDING()

In [318]:
df.isnull().sum()

CRIM            0
ZN              0
INDUS           0
POLINDEX        0
RM              0
AGE             0
DIS             0
HIGHWAYCOUNT    0
TAX             0
PTRATIO         0
IMM             0
BPL             0
PRICE           0
RIVERSIDE       0
dtype: int64

In [319]:
room=df[(df['RM']==-1)]
room['RM'].count()

np.int64(40)

In [320]:
neg=df[(df['AGE']<0)]
neg['AGE'].count()

np.int64(50)

In [321]:
df['AGE'].isnull().sum()

np.int64(0)

In [322]:
df['RIVERSIDE'].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [323]:
riverside=df[(df['RIVERSIDE']=='UNKNOWN')]
riverside['RIVERSIDE'].count()

np.int64(88)

In [324]:
river=df[(df['RIVERSIDE']=='YES') &  (df['AGE']<=50) & (df['AGE']>0) & (df['RIVERSIDE']!='UNKNOWN')]
river[['RIVERSIDE','AGE']].count()

RIVERSIDE    44
AGE          44
dtype: int64

In [325]:
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4.366543,1.159592,22.230240,1.146936,6.0,96.0,2.332414,6,403.809266,15.810504,354.065893,21.902957,16.375222,NO
3996,9.132894,0.294115,18.741019,0.876901,6.0,100.0,2.509486,24,666.000417,20.548310,394.997535,19.940826,9.565996,NO
3997,0.859468,21.201881,4.098201,1.142168,7.0,102.0,2.187747,7,264.067049,14.606753,392.096041,7.669832,30.106096,NO
3998,0.587681,45.399856,3.706238,1.719303,8.0,22.0,7.631113,6,398.613388,16.722867,378.734812,6.364646,37.403409,NO
3999,5.143827,0.000920,18.599543,0.864198,7.0,89.0,3.720523,24,666.587599,22.423092,392.552040,14.793550,20.204362,NO

In [326]:
# highway=df[((df['HIGHWAYCOUNT']==6) or (df['HIGHWAYCOUNT']==7) or (df['HIGHWAYCOUNT']==8))]

In [327]:


df['CATEGORY']=df['PRICE'].apply(lambda x: 1 if x<10 else 2 if 10<=x<20 else 3 if 20<=x<30 else 4 if 30<=x<40 else 5 if x>=40 else None)

In [328]:

df['CATEGORY'].value_counts()
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE,CATEGORY
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO,3
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO,3
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO,2
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO,3
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4.366543,1.159592,22.230240,1.146936,6.0,96.0,2.332414,6,403.809266,15.810504,354.065893,21.902957,16.375222,NO,2
3996,9.132894,0.294115,18.741019,0.876901,6.0,100.0,2.509486,24,666.000417,20.548310,394.997535,19.940826,9.565996,NO,1
3997,0.859468,21.201881,4.098201,1.142168,7.0,102.0,2.187747,7,264.067049,14.606753,392.096041,7.669832,30.106096,NO,4
3998,0.587681,45.399856,3.706238,1.719303,8.0,22.0,7.631113,6,398.613388,16.722867,378.734812,6.364646,37.403409,NO,4
3999,5.143827,0.000920,18.599543,0.864198,7.0,89.0,3.720523,24,666.587599,22.423092,392.552040,14.793550,20.204362,NO,3

In [329]:
import numpy as np
df[['RIVERSIDE','AGE','RM']]=df[['RIVERSIDE','AGE','RM']].fillna(np.nan)

In [330]:
X=df.drop('PRICE',axis=1)
y=df['PRICE']

In [331]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [332]:
X_train.shape

(2800, 14)

In [333]:
# Step 1
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE,CATEGORY
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO,3
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO,3
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO,2
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO,3
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4.366543,1.159592,22.230240,1.146936,6.0,96.0,2.332414,6,403.809266,15.810504,354.065893,21.902957,16.375222,NO,2
3996,9.132894,0.294115,18.741019,0.876901,6.0,100.0,2.509486,24,666.000417,20.548310,394.997535,19.940826,9.565996,NO,1
3997,0.859468,21.201881,4.098201,1.142168,7.0,102.0,2.187747,7,264.067049,14.606753,392.096041,7.669832,30.106096,NO,4
3998,0.587681,45.399856,3.706238,1.719303,8.0,22.0,7.631113,6,398.613388,16.722867,378.734812,6.364646,37.403409,NO,4
3999,5.143827,0.000920,18.599543,0.864198,7.0,89.0,3.720523,24,666.587599,22.423092,392.552040,14.793550,20.204362,NO,3

In [334]:
df=df.drop('CATEGORY',axis=1)
df

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4.366543,1.159592,22.230240,1.146936,6.0,96.0,2.332414,6,403.809266,15.810504,354.065893,21.902957,16.375222,NO
3996,9.132894,0.294115,18.741019,0.876901,6.0,100.0,2.509486,24,666.000417,20.548310,394.997535,19.940826,9.565996,NO
3997,0.859468,21.201881,4.098201,1.142168,7.0,102.0,2.187747,7,264.067049,14.606753,392.096041,7.669832,30.106096,NO
3998,0.587681,45.399856,3.706238,1.719303,8.0,22.0,7.631113,6,398.613388,16.722867,378.734812,6.364646,37.403409,NO
3999,5.143827,0.000920,18.599543,0.864198,7.0,89.0,3.720523,24,666.587599,22.423092,392.552040,14.793550,20.204362,NO

In [335]:
df['RIVERSIDE']=df['RIVERSIDE'].fillna(df['RIVERSIDE'].mode()[0])
df['AGE']=df['AGE'].fillna(df['AGE'].mean())
df['RM']=df['RM'].fillna(df['RM'].median())

In [336]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train[['CRIM', 'ZN','POLINDEX', 'RM', 'AGE', 'DIS', 'HIGHWAYCOUNT',
       'TAX', 'PTRATIO', 'IMM', 'BPL']]=scaler.fit_transform(X_train[['CRIM', 'ZN','POLINDEX', 'RM', 'AGE', 'DIS', 'HIGHWAYCOUNT',
       'TAX', 'PTRATIO', 'IMM', 'BPL']])

In [337]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
encoded=one.fit_transform(X_train[['RIVERSIDE','INDUS']])

In [338]:
encoded.shape

(2800, 2803)