<a href="https://colab.research.google.com/github/24f3003274-RISHABH/IITMBS_ML_DL_GEN_AI/blob/main/MLP/MLP_GA_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("/content/GA_2_dataset.csv")

In [34]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [36]:
df.dtypes

PlayerID                       int64
Age                          float64
Gender                        object
Location                      object
GameGenre                     object
PlayTimeHours                float64
InGamePurchases              float64
GameDifficulty                object
SessionsPerWeek                int64
AvgSessionDurationMinutes      int64
PlayerLevel                    int64
AchievementsUnlocked           int64
EngagementLevel               object
dtype: object

In [37]:
# df['InGamePurchases']=df['InGamePurchases'].fillna(0.0)

In [38]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [145]:
count=df[(df['Gender']=='Male')&(df['Location']=='Europe') & (df['InGamePurchases']==1.0)].shape[0]
count

299

In [146]:
count = len(df[(df['Gender']=='Male') & (df['Location']=='Europe') & (df['InGamePurchases']==1.0)])
count

299

In [147]:
players=df[(df['Age']<18.0) & (df['PlayTimeHours']>10.0)].shape[0]
players

453

In [148]:
players = len(df[(df['Age'] < 18) & (df['PlayTimeHours'] > 10)])
players

453

In [149]:
X = df.drop('EngagementLevel', axis=1)
y=df['EngagementLevel']
X.head(),y.head()

(   PlayerID   Age  Gender Location   GameGenre  PlayTimeHours  \
 0     35900  37.0    Male    Other    Strategy      23.929404
 1     27085  25.0    Male      NaN      Action      22.755168
 2     39595  24.0  Female   Europe  Simulation      19.505292
 3     37440  26.0  Female   Europe         RPG      11.009645
 4     22882  17.0  Female      USA         RPG       0.581039

    InGamePurchases GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  \
 0              NaN           Hard                3                        124
 1              1.0           Easy               14                         84
 2              0.0           Hard                3                        172
 3              NaN            NaN                3                         83
 4              1.0         Medium                5                        163

    PlayerLevel  AchievementsUnlocked
 0           99                    18
 1           84                    12
 2            9                    18
 3           36                    43
 4            9                    24  ,
 0    Medium
 1    Medium
 2    Medium
 3       Low
 4    Medium
 Name: EngagementLevel, dtype: object)

In [150]:
df

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42828,22.0,Female,USA,Sports,21.336213,0.0,Medium,13,58,74,15,Medium
9996,18169,21.0,Male,Europe,Strategy,6.158520,0.0,Easy,4,10,77,27,Low
9997,22094,43.0,Male,USA,Action,22.628880,0.0,Easy,4,161,66,46,Medium
9998,42490,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32,Medium
9999,42839,45.0,Male,Other,Simulation,22.067866,1.0,Easy,4,131,10,24,Medium

In [151]:
df.isnull().sum().sum()
# How many total null values were present in the whole dataset ?

np.int64(3337)

In [152]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [153]:
y_train.min()
y_train

9254    Medium
1561    Medium
1670      High
6087    Medium
6669      High
         ...
5734    Medium
5191    Medium
5390    Medium
860     Medium
7270    Medium
Name: EngagementLevel, Length: 8000, dtype: object

In [154]:
print(y_train.value_counts())

EngagementLevel
Medium    3983
Low       2021
High      1996
Name: count, dtype: int64

In [155]:
least_category = y_train.value_counts().idxmin()
least_count = y_train.value_counts().min()

print("Least category:", least_category)
print("Count:", least_count)

Least category: High
Count: 1996

In [156]:
X_test['Age']=X_test['Age'].fillna(X_test['Age'].mean())
X_test['Age'].sum()

np.float64(63598.91304347826)

In [157]:
X_test['Age']=X_test['Age'].fillna(X_test['Age'].mean())
X_train['Age']=X_train['Age'].fillna(X_train['Age'].mean())

# X_test['Location']=X_test['Location'].fillna("Other")
# X_train['Location']=X_train['Location'].fillna("Other")

# Calculate mode from training set
mode_value = X_train['GameDifficulty'].mode()[0]

# Fill missing values in both train and test
X_train['GameDifficulty'] = X_train['GameDifficulty'].fillna(mode_value)
X_test['GameDifficulty']  = X_test['GameDifficulty'].fillna(mode_value)

X_test['InGamePurchases']=X_test['InGamePurchases'].fillna(0.0)
X_train['InGamePurchases']=X_train['InGamePurchases'].fillna(0.0)

In [158]:
X_train.columns

Index(['PlayerID', 'Age', 'Gender', 'Location', 'GameGenre', 'PlayTimeHours',
       'InGamePurchases', 'GameDifficulty', 'SessionsPerWeek',
       'AvgSessionDurationMinutes', 'PlayerLevel', 'AchievementsUnlocked'],
      dtype='object')

In [159]:
# Replace NaN values in Location with "Other"
X_train['Location'] = X_train['Location'].fillna("Other")
X_test['Location']  = X_test['Location'].fillna("Other")

In [160]:
print(X_train.isnull().sum())
print(X_test.isnull().sum())

PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
dtype: int64
PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
dtype: int64

In [161]:
X_train=X_train.drop('PlayerID',axis=1)
X_test=X_test.drop('PlayerID',axis=1)

In [162]:
difficulty_map = {'Easy': 0, 'Medium': 1, 'Hard': 2}
X_train['GameDifficulty'] = X_train['GameDifficulty'].map(difficulty_map)
X_test['GameDifficulty'] = X_test['GameDifficulty'].map(difficulty_map)
X_train.head(20)

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
9254,34.000000,Female,Asia,Simulation,15.777862,0.0,1,5,76,80,33
1561,41.000000,Male,USA,Strategy,3.044182,0.0,1,7,73,34,5
1670,48.000000,Female,USA,Simulation,0.585613,0.0,1,16,163,44,3
6087,19.000000,Male,Europe,Action,6.194149,0.0,0,6,87,26,33
6669,38.000000,Male,Europe,RPG,21.610488,0.0,0,14,116,39,14
5933,42.000000,Male,Other,Sports,9.015849,0.0,0,2,22,48,43
8829,31.713995,Male,Asia,Strategy,1.959525,0.0,1,17,62,83,14
7945,39.000000,Male,USA,Action,16.550580,0.0,2,16,30,83,4
3508,42.000000,Male,USA,Action,14.366578,0.0,0,14,103,26,16
2002,43.000000,Male,Other,RPG,10.925802,0.0,0,12,111,47,32
5866,32.000000,Male,Asia,Action,13.611701,0.0,2,9,155,34,15
168,33.000000,Female,Asia,Action,15.606345,0.0,1,18,179,6,24
2588,38.000000,Female,Other,Sports,23.942772,0.0,0,13,95,99,36
5905,21.000000,Male,Other,RPG,0.817111,0.0,0,11,107,65,23
9529,33.000000,Male,Other,Simulation,5.896598,0.0,0,15,16,85,15
6384,42.000000,Male,USA,Strategy,21.232266,0.0,0,19,52,43,2
7824,37.000000,Male,USA,RPG,14.299752,0.0,0,11,71,56,30
9779,18.000000,Male,Asia,Action,9.228969,0.0,2,13,155,4,25
4629,19.000000,Female,USA,Simulation,18.036035,0.0,2,2,78,1,4
8560,38.000000,Male,Other,Simulation,12.506290,1.0,0,19,75,94,38

In [163]:
X_train=pd.get_dummies(X_train,columns=['Gender','Location','GameGenre'], drop_first=True)
X_test=pd.get_dummies(X_test,columns=['Gender','Location','GameGenre'], drop_first=True)
X

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42828,22.0,Female,USA,Sports,21.336213,0.0,Medium,13,58,74,15
9996,18169,21.0,Male,Europe,Strategy,6.158520,0.0,Easy,4,10,77,27
9997,22094,43.0,Male,USA,Action,22.628880,0.0,Easy,4,161,66,46
9998,42490,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32
9999,42839,45.0,Male,Other,Simulation,22.067866,1.0,Easy,4,131,10,24

In [164]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)   # learn params from train
X_test_scaled = scaler.transform(X_test)         # apply same params to test

In [165]:
import numpy as np
sum_first5 = np.sum(X_test_scaled[:5])
print(round(sum_first5, 2))

-7.16

6252      High
4684       Low
1731       Low
4742       Low
4521       Low
         ...
6412       Low
8285      High
7853    Medium
1095      High
6929       Low
Name: EngagementLevel, Length: 2000, dtype: object