<a href="https://colab.research.google.com/github/24f3003274-RISHABH/IITMBS_ML_DL_GEN_AI/blob/main/MLP/MLP_GA_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("/content/GA_2_dataset.csv")

In [34]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [36]:
df.dtypes

PlayerID                       int64
Age                          float64
Gender                        object
Location                      object
GameGenre                     object
PlayTimeHours                float64
InGamePurchases              float64
GameDifficulty                object
SessionsPerWeek                int64
AvgSessionDurationMinutes      int64
PlayerLevel                    int64
AchievementsUnlocked           int64
EngagementLevel               object
dtype: object

In [37]:
# df['InGamePurchases']=df['InGamePurchases'].fillna(0.0)

In [38]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [39]:
count=df[(df['Gender']=='Male')&(df['Location']=='Europe') & (df['InGamePurchases']==1.0)].shape[0]
count

299

In [40]:
count = len(df[(df['Gender']=='Male') & (df['Location']=='Europe') & (df['InGamePurchases']==1.0)])
count

299

In [41]:
players=df[(df['Age']<18.0) & (df['PlayTimeHours']>10.0)].shape[0]
players

453

In [42]:
players = len(df[(df['Age'] < 18) & (df['PlayTimeHours'] > 10)])
players

453

In [60]:
X = df.drop('EngagementLevel', axis=1)
y=df['EngagementLevel']
X.head(),y.head()

(   PlayerID   Age  Gender Location   GameGenre  PlayTimeHours  \
 0     35900  37.0    Male    Other    Strategy      23.929404
 1     27085  25.0    Male      NaN      Action      22.755168
 2     39595  24.0  Female   Europe  Simulation      19.505292
 3     37440  26.0  Female   Europe         RPG      11.009645
 4     22882  17.0  Female      USA         RPG       0.581039

    InGamePurchases GameDifficulty  SessionsPerWeek  AvgSessionDurationMinutes  \
 0              NaN           Hard                3                        124
 1              1.0           Easy               14                         84
 2              0.0           Hard                3                        172
 3              NaN            NaN                3                         83
 4              1.0         Medium                5                        163

    PlayerLevel  AchievementsUnlocked
 0           99                    18
 1           84                    12
 2            9                    18
 3           36                    43
 4            9                    24  ,
 0    Medium
 1    Medium
 2    Medium
 3       Low
 4    Medium
 Name: EngagementLevel, dtype: object)

In [62]:
df

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42828,22.0,Female,USA,Sports,21.336213,0.0,Medium,13,58,74,15,Medium
9996,18169,21.0,Male,Europe,Strategy,6.158520,0.0,Easy,4,10,77,27,Low
9997,22094,43.0,Male,USA,Action,22.628880,0.0,Easy,4,161,66,46,Medium
9998,42490,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32,Medium
9999,42839,45.0,Male,Other,Simulation,22.067866,1.0,Easy,4,131,10,24,Medium

In [66]:
df.isnull().sum().sum()
# How many total null values were present in the whole dataset ?

np.int64(3337)

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [72]:
y_train.min()
y_train

9254    Medium
1561    Medium
1670      High
6087    Medium
6669      High
         ...
5734    Medium
5191    Medium
5390    Medium
860     Medium
7270    Medium
Name: EngagementLevel, Length: 8000, dtype: object

In [73]:
print(y_train.value_counts())

EngagementLevel
Medium    3983
Low       2021
High      1996
Name: count, dtype: int64

In [74]:
least_category = y_train.value_counts().idxmin()
least_count = y_train.value_counts().min()

print("Least category:", least_category)
print("Count:", least_count)

Least category: High
Count: 1996