<a href="https://colab.research.google.com/github/24f3003274-RISHABH/IITMBS_ML_DL_GEN_AI/blob/main/MLP/MLP_GA_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("/content/GA_2_dataset.csv")

In [34]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [35]:
df.dtypes

PlayerID                       int64
Age                          float64
Gender                        object
Location                      object
GameGenre                     object
PlayTimeHours                float64
InGamePurchases              float64
GameDifficulty                object
SessionsPerWeek                int64
AvgSessionDurationMinutes      int64
PlayerLevel                    int64
AchievementsUnlocked           int64
EngagementLevel               object
dtype: object

In [12]:
# df['InGamePurchases']=df['InGamePurchases'].fillna(0.0)

In [13]:
df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,0.0,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,0.0,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium

In [25]:
count=df[(df['Gender']=='Male')&(df['Location']=='Europe') & (df['InGamePurchases']==1.0)].shape[0]
count

299

In [26]:
count = len(df[(df['Gender']=='Male') & (df['Location']=='Europe') & (df['InGamePurchases']==1.0)])
count

299

In [30]:
players=df[(df['Age']<18.0) & (df['PlayTimeHours']>10.0)].shape[0]
players

453

In [31]:
players = len(df[(df['Age'] < 18) & (df['PlayTimeHours'] > 10)])
players

453